### ISSUE TITLE
I see some duplicates and some elder versions

### ISSUE THREAD

**Issue by GoLangsam** [AungMyoKyaw/Myanmar-Unicode-Fonts#1]
This is a great collection - and I am happy I stumbled upon it.

Comparing with my (private) collection, I spot a few things such as binary duplicates,
and some elder versions (e.g. MyanmarCensus, MyanmarAngoun ...)

I'd be happy to provide PR's - please let me know.

**Comment by AungMyoKyaw** [comment]
![PRs Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square)

You are welcome.
